### ISSUE TITLE
WebP animated support

### ISSUE THREAD

**Issue by phanturne** [discord/lilliput#121]
I'm trying to use animated WebP for my Discord bot, but it's not supported by Discord. I noticed that there's an open pull request https://github.com/discord/lilliput/pull/103 for this feature. Does Discord have any plans on supporting animated WebP?

WebP has higher quality and has better compression than GIFs. It also supports 24-bit RGB color while GIF is limited to 8-bit color.

**Comment by brian-armstrong-discord** [comment]
Closing for duplicate issue

**Comment by phanturne** [comment]
Unfortunately, mp4 doesn't automatically play on Discord. I want to use animated card images. 

Thanks though.

**Comment by defunky** [comment]
@brian-armstrong-discord I can't find the duplicate issue? Is there any plans to merge in the PR, it's been sat there since October last year with no movement?

**Comment by BlackBeltPanda** [comment]
Where's the original issue this is duplicating? Would also love to see animated WebP support.

**Comment by nikooo777** [comment]
why is that pull request pending and not being merged?
Is something missing? why is the discussion on the pull request not possible then?

It would be nice to have some clarity, the PR is from 2022, webp is becoming more and more the standard, it'd be nice to have this integrated.
