### ISSUE TITLE
illegal instruction (core dumped) error, when trying to install

### ISSUE THREAD

**Issue by VaheGrigorian** [discord/lilliput#39]
Hi, I'm trying to run the example code on ubuntu 16.04 but getting 

> illegal instruction (core dumped)

 error, when trying to install.Do I need to install the c dependencies

**Comment by brian-armstrong-discord** [comment]
No, you shouldn't need them.

What is the command you're running when you see that?

**Comment by brian-armstrong-discord** [comment]
Is it possible you're on x86, not x86-64? I think this might only support 64-bit.
