### ISSUE TITLE
PNGs with transparent borders have an artifact after resizing

### ISSUE THREAD

**Issue by MarquessV** [discord/lilliput#62]
We're having an issue with certain types of PNG images. For example, this 320x320 image of a tomato has a white background, but has transparent borders on the top and bottom of the image.

![tomato.png](https://user-images.githubusercontent.com/4324359/64976607-98015a00-d866-11e9-972a-47b4cb5ceef1.png)

After resizing to 250x250 with lilliput we get this image

![tomato_out](https://user-images.githubusercontent.com/4324359/64976832-1827bf80-d867-11e9-8750-2730f23db213.png)

We get a visible dark line where the transparent borders begin on the original image. We've messed about with different PNG compression levels to no avail. Any ideas on how we can fix this?

**Comment by skidder** [comment]
This has been fixed with #169 
As you noted, the black bars resulted from not handling the alpha channel areas of the source image.
Thanks for reporting, and apologies for not resolving this sooner!
