### ISSUE TITLE
The effect of Discord increasingly relying on rust on this project

### ISSUE THREAD

**Issue by mocsy** [discord/lilliput#74]
Since Discord is increasingly relying on rust for performance critical use-cases, the question arises whether or not there are plans for lilliput to be oxidised as well.

Lilliput is also a very performance sensitive application.
Plus lilliput is a library, and calling go libs from other languages have a non-trivial overhead due to the runtime and the gc and all that.

https://blog.discord.com/why-discord-is-switching-from-go-to-rust-a190bbca2b1f

**Comment by NurMarvin** [comment]
Ah yes, RIIR :^) 
Honestly though, why go through the effort of rewriting it when the current version isn't causing any issues? It's not like the Go version is a big performance bottleneck for Discord,so there isn't really a reason for them to rewrite it in Rust except for the sake of it.

**Comment by mocsy** [comment]
> for
> 
> Ah yes, RIIR :^)
> Honestly though, why go through the effort of rewriting it when the current version isn't causing any issues?

'Why' is irrelevant to my question, which was about what's on the roadmap.

> It's not like the Go version is a big performance bottleneck for Discord,so there isn't really a reason for them to rewrite it in Rust except for the sake of it.

The 'Why' I offered here is, the fact that the current one is problematic to integrate into any non-go software.
Discord uses multiple languages to build their systems.
Being able to link the lib could be a benefit other than performance.

To that end C would work too, but Discord devs are known to use Rust, so it's more likely.

It's up to their project management to judge if the benefits are worth the investment for them or not. 
I don't see the big picture to judge that, and most likely neither are you. They should, that's why it is a question about plans rather than anything else.

For people who fear or generally oppose RIIR for other reasons, it's also an interesting question.
