### ISSUE TITLE
Can not build the lib

### ISSUE THREAD

**Issue by dubrovine** [discord/lilliput#78]
Hello there. 
I am stack for a couple of days 

can not build the lilliput under the alpine linux in docker

here is the full error : https://pastebin.com/ZZrK12Xh

this is what I fetching in container 

`RUN apk add --no-cache --virtual .fetch-deps \
    libtirpc-dev \
    libtirpc \
    procps \
    imlib2 \
    gcc \
    ca-certificates \
    curl \
    nano \
    file \
    ffmpeg \
    gawk \
    build-base \
    linux-headers \
    autoconf \
    nasm \
    cmake \
    libtool \
    automake`

but still had no luck :(

is there anything else I need to do ?

**Comment by brian-armstrong-discord** [comment]
Hello,

Does running build-deps-linux.sh work for you? https://github.com/discord/lilliput/blob/master/deps/build-deps-linux.sh

Once the script finishes, you'll want to make sure the deps it builds are in the repo where lilliput is.

It may just be that the static libraries included (built on ubuntu 18) are not compatible with your system.

**Comment by dubrovine** [comment]
Yes I am using this script but I have copied it to the /myappfolder/deps/build-deps-linux.sh

And executing it from there.

Do you mean that I need to execute it exactly under lillliput/deps folder ?

Thanx in advance

**Comment by dubrovine** [comment]
Everything is working fine if script was executed under the lilliput library. thank you. closing the issue

**Comment by dvaldivia** [comment]
@dubrovine can you share your dockerifle?
