### ISSUE TITLE
Some .gifs are incorrectly "smearing"

### ISSUE THREAD

**Issue by mcpower** [discord/lilliput#84]
| Input | Output |
| - | - |
| ![input](https://user-images.githubusercontent.com/6015058/106580059-91779d80-6595-11eb-93cd-6b65321e06a4.gif) | ![output](https://user-images.githubusercontent.com/6015058/106583289-09939280-6599-11eb-959a-9d77f9892066.gif) |

To reproduce:

1. `go get github.com/discord/lilliput`
2. `cd ~/go/src/github.com/discord/lilliput/examples`
3. `go build`
4. `./examples -input input.gif -output output.gif`

Alternatively, upload the input gif to Discord to reproduce.

Using GIMP to inspect the output gif, it seems like Lilliput is incorrectly outputting transparent pixels when it shouldn't be.

(The gif provided here is a minimal reproducible example, which is spliced from a longer gif - that's why there are transparent bars in the gif. I can upload the full gif if needed.)

**Comment by skidder** [comment]
Thank you for reporting this! I've been able to reproduce this issue when transforming from GIF->GIF. It doesn't occur when going from GIF->animated WebP. I agree that this is likely related to the handling of transparent pixels and the transparency threshold. We'll post an update once this is corrected. Thanks again!
