### ISSUE TITLE
Versions not picked up by pkg.go.dev

### ISSUE THREAD

**Issue by JeremyLoy** [discord/lilliput#96]
https://pkg.go.dev/github.com/discord/lilliput

I think it’s because this repository’s version tags are missing PATCH. e.g. v1.2 should instead be v1.2.0

instead, pseudo version numbers are automatically getting picked up by the module proxy https://golang.org/doc/modules/version-numbers#pseudo-version-number

it should be fairly easy to add new tags to existing releases which include PATCH

**Comment by skidder** [comment]
Thanks for raising this, I created patch-versioned tags retroactively and will make sure we use this versioning scheme for future releases:

```
→ git log --no-walk --tags --pretty="%h %d %s" --decorate=full
5acabb9  (tag: refs/tags/v1.3.0, tag: refs/tags/v1.3) Only Intel OSX (#139)
e611eea  (tag: refs/tags/v1.2.0, tag: refs/tags/v1.2, tag: refs/tags/1.2) Merge pull request #34 from nxnfufunezn/jpeg_progressive
6a7ecc6  (tag: refs/tags/v1.1.0, tag: refs/tags/v1.1) Merge pull request #14 from discordapp/bugfix/video_align
718cc27  (tag: refs/tags/v1.0.0, tag: refs/tags/v1.0) Merge pull request #12 from discordapp/feature/avcodec_orientation
```

**Comment by skidder** [comment]
I'll check back in a bit to see if it's indeed a caching issue. Within Discord we pull in Lilliput by git commit hash, not by tag.
